app = 'celupaz'

[http_service]
  internal_port = 8080  # IMPORTANTE
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[env]
  SPRING_PROFILES_ACTIVE = "dev"
