app = 'celupaz'
primary_region = 'dfw'

[env]
  SPRING_PROFILES_ACTIVE = 'dev,api-docs'
  SPRING_DATASOURCE_DRIVER_CLASS_NAME = "com.mysql.cj.jdbc.Driver"
  # Asegúrate de que esta URL sea correcta. Si no tienes una BD lista,
  # usa H2 para probar que el despliegue funciona:
  # SPRING_DATASOURCE_URL = "jdbc:h2:mem:celupaz;DB_CLOSE_DELAY=-1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  
  [http_service.concurrency]
    type = 'requests'
    soft_limit = 200
    hard_limit = 250

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.health_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "120s" # 2 minutos para que JHipster respire al arrancar
    method = "get"
    path = "/management/health/liveness"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
