# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjlkMzc0OWVjMzAwYjRhODQ0MjljZWQ1ZjVjYzFhM2IxY2M0YzlkNmVmY2ZmZTVlNzliZDcyZTE3YjVhMTgwZmQzZGFjYmM2ZTUyODMzNWJmN2I3M2RkOGM4OGFmNWVjM2NlY2M3YTU3MjJlZjg4MmQ4NTFhYTVhZDJjNDc2MTA=
