# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjI3YjBiNjY2ZThhZGFiNzZjNTdlN2RlZTA3ZjliNzNhMzhhMzYwOWE1OTQ1MmVmYzkzM2UyN2UwMWJiOTFlOWFiNGQwMTYzNGQ4NTJkZWU5OTMwNjM1NDBjMjI5MzkzMzViZjdjZDE1ZmY4NmZlN2E4OGY2Y2JjNjBmMTEyYjk=
