spring:
  datasource:
    username: root
    password: mypass

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjlkMzc0OWVjMzAwYjRhODQ0MjljZWQ1ZjVjYzFhM2IxY2M0YzlkNmVmY2ZmZTVlNzliZDcyZTE3YjVhMTgwZmQzZGFjYmM2ZTUyODMzNWJmN2I3M2RkOGM4OGFmNWVjM2NlY2M3YTU3MjJlZjg4MmQ4NTFhYTVhZDJjNDc2MTA=
