package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaAllPropertiesEquals(Alma expected, Alma actual) {
        assertAlmaAutoGeneratedPropertiesEquals(expected, actual);
        assertAlmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaAllUpdatablePropertiesEquals(Alma expected, Alma actual) {
        assertAlmaUpdatableFieldsEquals(expected, actual);
        assertAlmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaAutoGeneratedPropertiesEquals(Alma expected, Alma actual) {
        assertThat(actual)
            .as("Verify Alma auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaUpdatableFieldsEquals(Alma expected, Alma actual) {
        assertThat(actual)
            .as("Verify Alma relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()))
            .satisfies(a -> assertThat(a.getMunicipality()).as("check municipality").isEqualTo(expected.getMunicipality()))
            .satisfies(a -> assertThat(a.getColony()).as("check colony").isEqualTo(expected.getColony()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFoto()).as("check foto").isEqualTo(expected.getFoto()))
            .satisfies(a -> assertThat(a.getFotoContentType()).as("check foto content type").isEqualTo(expected.getFotoContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaUpdatableRelationshipsEquals(Alma expected, Alma actual) {
        // empty method
    }
}
