package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlmaHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaHistoryAllPropertiesEquals(AlmaHistory expected, AlmaHistory actual) {
        assertAlmaHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertAlmaHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaHistoryAllUpdatablePropertiesEquals(AlmaHistory expected, AlmaHistory actual) {
        assertAlmaHistoryUpdatableFieldsEquals(expected, actual);
        assertAlmaHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaHistoryAutoGeneratedPropertiesEquals(AlmaHistory expected, AlmaHistory actual) {
        assertThat(actual)
            .as("Verify AlmaHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaHistoryUpdatableFieldsEquals(AlmaHistory expected, AlmaHistory actual) {
        assertThat(actual)
            .as("Verify AlmaHistory relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlmaHistoryUpdatableRelationshipsEquals(AlmaHistory expected, AlmaHistory actual) {
        assertThat(actual)
            .as("Verify AlmaHistory relationships")
            .satisfies(a -> assertThat(a.getAlma()).as("check alma").isEqualTo(expected.getAlma()))
            .satisfies(a -> assertThat(a.getCell()).as("check cell").isEqualTo(expected.getCell()))
            .satisfies(a -> assertThat(a.getRolcelula()).as("check rolcelula").isEqualTo(expected.getRolcelula()));
    }
}
