package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttendanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceAllPropertiesEquals(Attendance expected, Attendance actual) {
        assertAttendanceAutoGeneratedPropertiesEquals(expected, actual);
        assertAttendanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceAllUpdatablePropertiesEquals(Attendance expected, Attendance actual) {
        assertAttendanceUpdatableFieldsEquals(expected, actual);
        assertAttendanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceAutoGeneratedPropertiesEquals(Attendance expected, Attendance actual) {
        assertThat(actual)
            .as("Verify Attendance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceUpdatableFieldsEquals(Attendance expected, Attendance actual) {
        assertThat(actual)
            .as("Verify Attendance relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttendanceUpdatableRelationshipsEquals(Attendance expected, Attendance actual) {
        assertThat(actual)
            .as("Verify Attendance relationships")
            .satisfies(a -> assertThat(a.getMembercelula()).as("check membercelula").isEqualTo(expected.getMembercelula()))
            .satisfies(a -> assertThat(a.getPlanificacion()).as("check planificacion").isEqualTo(expected.getPlanificacion()));
    }
}
