package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CellTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellTypeAllPropertiesEquals(CellType expected, CellType actual) {
        assertCellTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCellTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellTypeAllUpdatablePropertiesEquals(CellType expected, CellType actual) {
        assertCellTypeUpdatableFieldsEquals(expected, actual);
        assertCellTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellTypeAutoGeneratedPropertiesEquals(CellType expected, CellType actual) {
        assertThat(actual)
            .as("Verify CellType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellTypeUpdatableFieldsEquals(CellType expected, CellType actual) {
        assertThat(actual)
            .as("Verify CellType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellTypeUpdatableRelationshipsEquals(CellType expected, CellType actual) {
        // empty method
    }
}
