package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CellAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellAllPropertiesEquals(Cell expected, Cell actual) {
        assertCellAutoGeneratedPropertiesEquals(expected, actual);
        assertCellAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellAllUpdatablePropertiesEquals(Cell expected, Cell actual) {
        assertCellUpdatableFieldsEquals(expected, actual);
        assertCellUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellAutoGeneratedPropertiesEquals(Cell expected, Cell actual) {
        assertThat(actual)
            .as("Verify Cell auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellUpdatableFieldsEquals(Cell expected, Cell actual) {
        assertThat(actual)
            .as("Verify Cell relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSector()).as("check sector").isEqualTo(expected.getSector()))
            .satisfies(a -> assertThat(a.getLider()).as("check lider").isEqualTo(expected.getLider()))
            .satisfies(a -> assertThat(a.getCordinador()).as("check cordinador").isEqualTo(expected.getCordinador()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCellUpdatableRelationshipsEquals(Cell expected, Cell actual) {
        assertThat(actual)
            .as("Verify Cell relationships")
            .satisfies(a -> assertThat(a.getCellType()).as("check cellType").isEqualTo(expected.getCellType()));
    }
}
