package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IglesiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIglesiaAllPropertiesEquals(Iglesia expected, Iglesia actual) {
        assertIglesiaAutoGeneratedPropertiesEquals(expected, actual);
        assertIglesiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIglesiaAllUpdatablePropertiesEquals(Iglesia expected, Iglesia actual) {
        assertIglesiaUpdatableFieldsEquals(expected, actual);
        assertIglesiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIglesiaAutoGeneratedPropertiesEquals(Iglesia expected, Iglesia actual) {
        assertThat(actual)
            .as("Verify Iglesia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIglesiaUpdatableFieldsEquals(Iglesia expected, Iglesia actual) {
        assertThat(actual)
            .as("Verify Iglesia relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIglesiaUpdatableRelationshipsEquals(Iglesia expected, Iglesia actual) {
        // empty method
    }
}
