package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAllPropertiesEquals(Member expected, Member actual) {
        assertMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAllUpdatablePropertiesEquals(Member expected, Member actual) {
        assertMemberUpdatableFieldsEquals(expected, actual);
        assertMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAutoGeneratedPropertiesEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberUpdatableFieldsEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()))
            .satisfies(a -> assertThat(a.getMunicipality()).as("check municipality").isEqualTo(expected.getMunicipality()))
            .satisfies(a -> assertThat(a.getColony()).as("check colony").isEqualTo(expected.getColony()))
            .satisfies(a -> assertThat(a.getIsCompaz()).as("check isCompaz").isEqualTo(expected.getIsCompaz()))
            .satisfies(a -> assertThat(a.getFechacumple()).as("check fechacumple").isEqualTo(expected.getFechacumple()))
            .satisfies(a -> assertThat(a.getPadre()).as("check padre").isEqualTo(expected.getPadre()))
            .satisfies(a -> assertThat(a.getRelacion()).as("check relacion").isEqualTo(expected.getRelacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberUpdatableRelationshipsEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member relationships")
            .satisfies(a -> assertThat(a.getIglesia()).as("check iglesia").isEqualTo(expected.getIglesia()));
    }
}
