package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberCelulaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberCelulaAllPropertiesEquals(MemberCelula expected, MemberCelula actual) {
        assertMemberCelulaAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberCelulaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberCelulaAllUpdatablePropertiesEquals(MemberCelula expected, MemberCelula actual) {
        assertMemberCelulaUpdatableFieldsEquals(expected, actual);
        assertMemberCelulaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberCelulaAutoGeneratedPropertiesEquals(MemberCelula expected, MemberCelula actual) {
        assertThat(actual)
            .as("Verify MemberCelula auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberCelulaUpdatableFieldsEquals(MemberCelula expected, MemberCelula actual) {
        assertThat(actual)
            .as("Verify MemberCelula relevant properties")
            .satisfies(a -> assertThat(a.getFechaCreada()).as("check fechaCreada").isEqualTo(expected.getFechaCreada()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberCelulaUpdatableRelationshipsEquals(MemberCelula expected, MemberCelula actual) {
        assertThat(actual)
            .as("Verify MemberCelula relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()))
            .satisfies(a -> assertThat(a.getCell()).as("check cell").isEqualTo(expected.getCell()));
    }
}
