package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanificacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanificacionAllPropertiesEquals(Planificacion expected, Planificacion actual) {
        assertPlanificacionAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanificacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanificacionAllUpdatablePropertiesEquals(Planificacion expected, Planificacion actual) {
        assertPlanificacionUpdatableFieldsEquals(expected, actual);
        assertPlanificacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanificacionAutoGeneratedPropertiesEquals(Planificacion expected, Planificacion actual) {
        assertThat(actual)
            .as("Verify Planificacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanificacionUpdatableFieldsEquals(Planificacion expected, Planificacion actual) {
        assertThat(actual)
            .as("Verify Planificacion relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanificacionUpdatableRelationshipsEquals(Planificacion expected, Planificacion actual) {
        assertThat(actual)
            .as("Verify Planificacion relationships")
            .satisfies(a -> assertThat(a.getAlmahistory()).as("check almahistory").isEqualTo(expected.getAlmahistory()))
            .satisfies(a -> assertThat(a.getPrivilege()).as("check privilege").isEqualTo(expected.getPrivilege()))
            .satisfies(a -> assertThat(a.getPlaniMaster()).as("check planiMaster").isEqualTo(expected.getPlaniMaster()));
    }
}
