package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaniMasterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaniMasterAllPropertiesEquals(PlaniMaster expected, PlaniMaster actual) {
        assertPlaniMasterAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaniMasterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaniMasterAllUpdatablePropertiesEquals(PlaniMaster expected, PlaniMaster actual) {
        assertPlaniMasterUpdatableFieldsEquals(expected, actual);
        assertPlaniMasterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaniMasterAutoGeneratedPropertiesEquals(PlaniMaster expected, PlaniMaster actual) {
        assertThat(actual)
            .as("Verify PlaniMaster auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaniMasterUpdatableFieldsEquals(PlaniMaster expected, PlaniMaster actual) {
        assertThat(actual)
            .as("Verify PlaniMaster relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getOfrenda()).as("check ofrenda").isEqualTo(expected.getOfrenda()))
            .satisfies(a -> assertThat(a.getVisitaCordinador()).as("check visitaCordinador").isEqualTo(expected.getVisitaCordinador()))
            .satisfies(a -> assertThat(a.getVisitaTutor()).as("check visitaTutor").isEqualTo(expected.getVisitaTutor()))
            .satisfies(a -> assertThat(a.getVisitaDirector()).as("check visitaDirector").isEqualTo(expected.getVisitaDirector()))
            .satisfies(a -> assertThat(a.getOtraVisita()).as("check otraVisita").isEqualTo(expected.getOtraVisita()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getDoneby()).as("check doneby").isEqualTo(expected.getDoneby()))
            .satisfies(a -> assertThat(a.getCompletado()).as("check completado").isEqualTo(expected.getCompletado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaniMasterUpdatableRelationshipsEquals(PlaniMaster expected, PlaniMaster actual) {
        // empty method
    }
}
