package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrivilegeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivilegeAllPropertiesEquals(Privilege expected, Privilege actual) {
        assertPrivilegeAutoGeneratedPropertiesEquals(expected, actual);
        assertPrivilegeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivilegeAllUpdatablePropertiesEquals(Privilege expected, Privilege actual) {
        assertPrivilegeUpdatableFieldsEquals(expected, actual);
        assertPrivilegeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivilegeAutoGeneratedPropertiesEquals(Privilege expected, Privilege actual) {
        assertThat(actual)
            .as("Verify Privilege auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivilegeUpdatableFieldsEquals(Privilege expected, Privilege actual) {
        assertThat(actual)
            .as("Verify Privilege relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrivilegeUpdatableRelationshipsEquals(Privilege expected, Privilege actual) {
        // empty method
    }
}
