package com.chrisgeek.celupaz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RolCelulaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolCelulaAllPropertiesEquals(RolCelula expected, RolCelula actual) {
        assertRolCelulaAutoGeneratedPropertiesEquals(expected, actual);
        assertRolCelulaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolCelulaAllUpdatablePropertiesEquals(RolCelula expected, RolCelula actual) {
        assertRolCelulaUpdatableFieldsEquals(expected, actual);
        assertRolCelulaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolCelulaAutoGeneratedPropertiesEquals(RolCelula expected, RolCelula actual) {
        assertThat(actual)
            .as("Verify RolCelula auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolCelulaUpdatableFieldsEquals(RolCelula expected, RolCelula actual) {
        assertThat(actual)
            .as("Verify RolCelula relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRolCelulaUpdatableRelationshipsEquals(RolCelula expected, RolCelula actual) {
        // empty method
    }
}
